# Copyright 2023 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Run all lint checks
name: lint
on:
  push:
    branches: ["main", "dev"]

jobs:
  run:
    name: Lint Scala Files
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Initialize and update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' &&
            github.ref_name == 'main' }}
          activate-environment: true
      - name: Check format
        run: |
          sbt scalafmtCheck
