
# Run Scala Unit Test
name: Run Scala Unit Test
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  run:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' &&
            github.ref_name == 'main' }}
          activate-environment: true
      - name: Run the unit tests
        run: |
          sbt test
